Models/ErrorViewModel.cs
namespace ProductivePomodoro.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using ProductivePomodoro.Models;
using System.Diagnostics;

namespace ProductivePomodoro.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/PomodoroController.cs
using Microsoft.AspNetCore.Mvc;

namespace ProductivePomodoro.Controllers
{
    public class PomodoroController : Controller
    {
        public IActionResult Timer()
        {
            return View();
        }

        public IActionResult Notes()
        {
            return View();
        }
    }
}

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Productive Pomodoro";
}

<div class="text-center" style="background:red">
    <h1 class="display-4">Productive Pomodoro</h1>
    <h3 class="display-6">A pomodoro timer designed to help you with your procrastination!</h3>
    <a class="btn btn-primary" asp-controller="Pomodoro" asp-action="Notes">See Notes</a>
</div>

Views/Pomodoro/Notes.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@

<h1>Oi</h1>
    

Views/Pomodoro/Timer.cshtml
@{
    ViewData["Title"] = "Pomodoro Timer";
}

<h2>Set your timer</h2>
<p>Choose how much time you will spend in each section<br />
    Determine your goals for each section<br />
    You can do this!
</p>

<div>
    <h4>Focus time</h4>
    <div>
        <input type="number" />
        <input type="number" />
    </div>
</div>

<div>
    <h4>Break time</h4>
    <div>
        <input type="number" />
        <input type="number" />
    </div>
</div>

<div>
    <h4>Long break</h4>
    <div>
        <input type="number" />
        <input type="number" />
    </div>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ProductivePomodoro</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ProductivePomodoro.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ProductivePomodoro</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - ProductivePomodoro - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>